"""added Geschaeftspartner

Revision ID: ed03bb4cfa84
Revises: efc0c44d61b4
Create Date: 2023-10-25 17:24:59.284090

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed03bb4cfa84"
down_revision: Union[str, None] = "efc0c44d61b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geschaeftspartner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name1", sa.String(length=30), nullable=False),
        sa.Column("gewerbekennzeichnung", sa.Boolean(), nullable=False),
        sa.Column(
            "geschaeftspartnerrolle",
            sa.ARRAY(
                sa.Enum(
                    "LIEFERANT", "DIENSTLEISTER", "KUNDE", "INTERESSENT", "MARKTPARTNER", name="Geschaeftspartnerrolle"
                )
            ),
            nullable=False,
        ),
        sa.Column("anrede", sa.Enum("HERR", "FRAU", "EHELEUTE", "FIRMA", "INDIVIDUELL", name="Anrede"), nullable=True),
        sa.Column("name2", sa.String(length=30), nullable=True),
        sa.Column("name3", sa.String(length=30), nullable=True),
        sa.Column("hrnummer", sa.String(length=30), nullable=True),
        sa.Column("amtsgericht", sa.String(length=30), nullable=True),
        sa.Column(
            "kontaktweg", sa.Enum("ANSCHREIBEN", "TELEFONAT", "FAX", "E_MAIL", "SMS", name="Kontaktart"), nullable=True
        ),
        sa.Column("umsatzsteuer_id", sa.String(length=30), nullable=True),
        sa.Column("glaeubiger_id", sa.String(length=30), nullable=True),
        sa.Column("e_mail_adresse", sa.String(length=30), nullable=True),
        sa.Column("website", sa.String(length=30), nullable=True),
        sa.Column("adresse_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["adresse_id"],
            ["adresse.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geschaeftspartner")
    # ### end Alembic commands ###
