"""init

Revision ID: d73a00baaa17
Revises:
Create Date: 2023-10-24 15:36:24.344118

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d73a00baaa17"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
