"""link Geschaeftspartner and Adresse

Revision ID: 56f7f9957902
Revises: 5b34fed21cc5
Create Date: 2023-09-27 09:23:35.510447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56f7f9957902"
down_revision: Union[str, None] = "5b34fed21cc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geschaeftspartner", sa.Column("adresse_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "geschaeftspartner", "adresse", ["adresse_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "geschaeftspartner", type_="foreignkey")
    op.drop_column("geschaeftspartner", "adresse_id")
    # ### end Alembic commands ###
