"""init adresse

Revision ID: 9d18ca349436
Revises: ee320e3ff02b
Create Date: 2023-09-26 15:23:42.009461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d18ca349436"
down_revision: Union[str, None] = "ee320e3ff02b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adresse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("postleitzahl", sa.String(length=30), nullable=False),
        sa.Column("ort", sa.String(length=30), nullable=False),
        sa.Column("ortsteil", sa.String(length=30), nullable=True),
        sa.Column("strasse", sa.String(length=30), nullable=True),
        sa.Column("hausnummer", sa.String(length=30), nullable=True),
        sa.Column("postfach", sa.String(length=30), nullable=True),
        sa.Column("adresszusatz", sa.String(length=30), nullable=True),
        sa.Column("co_ergaenzung", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("adresse")
    # ### end Alembic commands ###
