"""init geschaeftspartner

Revision ID: ee320e3ff02b
Revises: 463cdbe75f57
Create Date: 2023-09-26 15:19:19.533241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee320e3ff02b"
down_revision: Union[str, None] = "463cdbe75f57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geschaeftspartner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name1", sa.String(length=30), nullable=False),
        sa.Column("gewerbekennzeichnung", sa.Boolean(), nullable=False),
        sa.Column("name2", sa.String(length=30), nullable=True),
        sa.Column("name3", sa.String(length=30), nullable=True),
        sa.Column("hrnummer", sa.String(length=30), nullable=True),
        sa.Column("amtsgericht", sa.String(length=30), nullable=True),
        sa.Column("umsatzsteuer_id", sa.String(length=30), nullable=True),
        sa.Column("glaeubiger_id", sa.String(length=30), nullable=True),
        sa.Column("e_mail_adresse", sa.String(length=30), nullable=True),
        sa.Column("website", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("geschaeftspartner")
    # ### end Alembic commands ###
