name: "Coverage"

on: [push]
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Start containers required by integrationtests
        run: |
          cd postgresql_app
          python .\create_env_file.py
          docker-compose -f "docker-compose.yaml" up -d
      - name: Run Tests and Record Coverage
        run: |
          tox -e coverage
      - name: stop containers required by integrationtests
        run: |
          cd postgresql_app
          docker-compose -f "docker-compose.yaml" down -v
