name: "Coverage"

on: [push]
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --group coverage --group tests --group init_bo4e
      - name: Set up test database
        run: |
          cd src
          uv run python -m borm.db.postgresql_db.create_env_file
          docker compose -f borm/db/postgresql_db/docker-compose.yaml up -d
      - name: Pull and generate BO4E models
        run: |
          mkdir -p bo4e_schemas
          cd bo4e_schemas
          uv run bost -t v202401.0.1 -o ./
          uv run bo4e-generator -i ./ -o ../src/borm/models -ot sql_model
      - name: Run Tests and Record Coverage
        run: |
          cd tests
          uv run python -m borm
          uv run coverage run -m pytest
          uv run coverage html --omit tests/*,src/borm/models/*
          uv run coverage report --fail-under 80 --omit tests/*,src/borm/models/*
      - name: Tear down test database
        run: docker compose -f src/borm/db/postgresql_db/docker-compose.yaml down -v
