name: "Integrationtests"

on: [push]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: cp "src/borm/db/postgresql_db/.env.example" .env
      - name: Start containers
        run: docker compose -f "src/borm/db/postgresql_db/docker-compose.yaml" up -d
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run the Unit Tests via Tox
        run: |
          tox -e integrationtests
