name: "Unittests"

on: [push]
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: uv sync --group tests
      - name: Run the Unit Tests
        run: |
          cd src
          uv run python -m borm.db.postgresql_db.create_env_file
          docker compose -f borm/db/postgresql_db/docker-compose.yaml up -d
          cd borm/db/postgresql_db
          docker compose -f docker-compose.yaml down -v
